//! What the money and failure behaviour of the gateway **actually is**, measured.
//!
//! The two repositories this lab exists for make claims in their READMEs. Claims
//! become credible when someone else can reproduce the numbers, so this crate drives
//! the real `llmgateway` code — not a copy, not a mock of the gateway — with a fake
//! provider that can be told to fail in specific ways, and prints what happened.
//!
//! Three properties, because a measurement you cannot trust is worse than no
//! measurement:
//!
//! - **no network and no keys**: the provider is a trait implementation in this same
//!   process, so a full run takes milliseconds and never depends on someone else's
//!   availability or latency;
//! - **the invariants are assertions, not paragraphs**: `cargo test` fails if the cap
//!   stops holding or a denied request reaches the provider;
//! - **the numbers are in the repository**: `reports/latest.md` is generated by
//!   `make lab` and committed, so a reader can see the result before running anything.
//!
//! Scope limit, declared: this is the in-process core of the gateway. The HTTP
//! adapter and the agent side (an `agentloop` run driving this over the wire) are not
//! here yet — see the README.

pub mod e2e;

use std::collections::{BTreeMap, BTreeSet};
use std::path::Path;
use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{Duration, SystemTime, UNIX_EPOCH};

use llmgateway::auth::Authenticator;
use llmgateway::budget::{BudgetRegistry, Month, TenantBudget};
use llmgateway::gateway::{Gateway, GatewayConfig, GatewayRequest, GatewayResponse};
use llmgateway::meter::Meter;
use llmgateway::pricing::Price;
use llmgateway::request::inspect;
use llmgateway::router::Router;
use llmgateway::upstream::{
    boxed, BoxFuture, TransportError, TransportKind, Upstream, UpstreamRequest, UpstreamResponse,
};
use llmgateway::{micros, usd, MicroUsd, PriceTable};

/// The fixed clock every scenario runs on: 2026-01-01T00:00:00Z.
pub const NOW: i64 = 1_767_225_600_000;
/// The tenant every scenario acts as.
pub const TENANT: &str = "acme";
/// The API key of [`TENANT`].
pub const KEY: &str = "sk-acme";
/// The model every scenario asks for.
pub const MODEL: &str = "gpt-4o-mini";

/// What a fake provider is told to do, one entry per call. The last entry repeats.
#[derive(Debug, Clone)]
pub enum Behavior {
    /// A `200` whose body carries the usage the gateway meters.
    Ok {
        /// The text of the completion.
        content: String,
        /// Prompt tokens the provider reports.
        prompt_tokens: u64,
        /// Completion tokens the provider reports.
        completion_tokens: u64,
    },
    /// Any status and body, forwarded to the client as they are.
    Responds {
        /// The HTTP status.
        status: u16,
        /// The raw body.
        body: String,
    },
    /// Nothing comes back, and the request **did not leave** the gateway.
    NotSent,
    /// Nothing comes back, and the request **did leave**: retrying may charge twice.
    SentUnknown,
    /// A `200` in chunks, never accumulated into one body.
    Stream(Vec<String>),
}

/// A provider that does exactly what it is told and counts how many times.
#[derive(Debug)]
pub struct FakeProvider {
    name: String,
    models: Option<Vec<String>>,
    behaviors: Mutex<Vec<Behavior>>,
    calls: AtomicUsize,
}

impl FakeProvider {
    /// A provider that serves every model and follows `behaviors`.
    #[must_use]
    pub fn new(name: &str, behaviors: Vec<Behavior>) -> Self {
        Self {
            name: name.to_owned(),
            models: None,
            behaviors: Mutex::new(behaviors),
            calls: AtomicUsize::new(0),
        }
    }

    /// A provider that serves only `models`.
    #[must_use]
    pub fn serving(name: &str, models: &[&str], behaviors: Vec<Behavior>) -> Self {
        let mut provider = Self::new(name, behaviors);
        provider.models = Some(models.iter().map(|m| (*m).to_owned()).collect());
        provider
    }

    /// How many times the provider was actually called.
    #[must_use]
    pub fn calls(&self) -> usize {
        self.calls.load(Ordering::SeqCst)
    }

    fn next(&self) -> Behavior {
        let mut list = self.behaviors.lock().expect("behaviors lock");
        if list.is_empty() {
            return Behavior::Ok {
                content: "ok".to_owned(),
                prompt_tokens: 1_000,
                completion_tokens: 500,
            };
        }
        if list.len() == 1 {
            return list[0].clone();
        }
        list.remove(0)
    }
}

impl Upstream for FakeProvider {
    fn name(&self) -> &str {
        &self.name
    }

    fn models(&self) -> Option<&[String]> {
        self.models.as_deref()
    }

    fn send(
        &self,
        _request: UpstreamRequest,
        _timeout: Duration,
    ) -> BoxFuture<'_, Result<UpstreamResponse, TransportError>> {
        self.calls.fetch_add(1, Ordering::SeqCst);
        let behavior = self.next();
        let name = self.name.clone();

        boxed(move || async move {
            match behavior {
                Behavior::Ok {
                    content,
                    prompt_tokens,
                    completion_tokens,
                } => Ok(UpstreamResponse::buffered(
                    200,
                    ok_body(&content, prompt_tokens, completion_tokens),
                )),
                Behavior::Responds { status, body } => Ok(UpstreamResponse::buffered(status, body)),
                Behavior::NotSent => Err(TransportError::not_sent(
                    TransportKind::Connect,
                    format!("{name} refused the connection"),
                )),
                Behavior::SentUnknown => Err(TransportError::maybe_sent(
                    TransportKind::Timeout,
                    format!("{name} timed out after receiving the request"),
                )),
                Behavior::Stream(chunks) => Ok(UpstreamResponse::streaming(
                    200,
                    chunks.into_iter().map(String::into_bytes).collect(),
                )),
            }
        })
    }
}

/// The price list used by every scenario: light input, heavier output.
#[must_use]
pub fn prices() -> PriceTable {
    let mut map = BTreeMap::new();
    map.insert(
        MODEL.to_owned(),
        Price {
            input: micros(150),
            output: micros(600),
        },
    );
    PriceTable::new(map)
}

/// A gateway wired for one scenario, plus the counters it is being judged on.
#[derive(Debug)]
pub struct Lab {
    /// The gateway under measurement.
    pub gateway: Gateway,
    /// The meter: the money and the sampled metrics.
    pub meter: Arc<Meter>,
    /// The tenant cap.
    pub cap: Arc<TenantBudget>,
}

/// Builds a gateway with a tenant cap, a sample rate and a list of providers.
#[must_use]
pub fn lab(
    providers: Vec<Arc<FakeProvider>>,
    cap: MicroUsd,
    sample_rate: u64,
    max_attempts: usize,
) -> Lab {
    let prices = prices();
    let meter = Arc::new(Meter::new(prices.clone(), sample_rate));
    let budget = BudgetRegistry::new();
    let tenant_cap = budget.insert(TenantBudget::new(TENANT, cap, Month::of(NOW)), NOW);
    let no_restriction: BTreeSet<String> = BTreeSet::new();
    let gateway = Gateway::new(GatewayConfig {
        authenticator: Authenticator::new(
            &[(TENANT.to_owned(), KEY.to_owned())],
            &[(TENANT.to_owned(), no_restriction)],
        ),
        budget,
        meter: Arc::clone(&meter),
        router: Arc::new(Router::new(
            providers
                .into_iter()
                .map(|p| p as Arc<dyn Upstream>)
                .collect(),
            max_attempts,
            Duration::from_secs(5),
        )),
        prices,
        max_output_default: 4_096,
        timeout: Duration::from_secs(5),
        now: Arc::new(|| NOW),
    });
    Lab {
        gateway,
        meter,
        cap: tenant_cap,
    }
}

/// An OpenAI-compatible request body, byte for byte like a client would send it.
#[must_use]
pub fn request(max_tokens: u64, stream: bool) -> GatewayRequest {
    let body = format!(
        r#"{{"model":"{MODEL}","max_tokens":{max_tokens},"stream":{stream},"messages":[{{"role":"user","content":"hello"}}]}}"#
    );
    GatewayRequest {
        key: Some(KEY.to_owned()),
        body: body.into_bytes(),
    }
}

/// One request's outcome, with everything needed to judge it.
#[derive(Debug, Clone)]
pub struct SingleRun {
    /// The status the client saw.
    pub status: u16,
    /// Who served it, if a provider did.
    pub provider: Option<String>,
    /// Calls per provider, so a skipped or untried provider is visible.
    pub calls: Vec<(String, usize)>,
    /// Money spent.
    pub spent: MicroUsd,
    /// Money still reserved: must be zero at the end of any request.
    pub held: MicroUsd,
    /// Whether the response was forwarded as a stream.
    pub streamed: bool,
}

/// Sends one request and reads the counters afterwards.
pub async fn one(providers: &[Arc<FakeProvider>], max_tokens: u64, stream: bool) -> SingleRun {
    let l = lab(providers.to_vec(), usd(1.0).expect("valid cap"), 1, 4);
    run_one(&l, providers, max_tokens, stream).await
}

async fn run_one(
    l: &Lab,
    providers: &[Arc<FakeProvider>],
    max_tokens: u64,
    stream: bool,
) -> SingleRun {
    let response = l.gateway.handle(request(max_tokens, stream)).await;
    SingleRun {
        status: response.status(),
        provider: response.provider().map(str::to_owned),
        calls: providers
            .iter()
            .map(|p| (p.name.clone(), p.calls()))
            .collect(),
        spent: l.meter.spent(TENANT),
        held: l.cap.held(NOW),
        streamed: matches!(response, GatewayResponse::Stream { .. }),
    }
}

/// What a capped run of many requests produced.
#[derive(Debug, Clone)]
pub struct CappedRun {
    /// Requests sent by the client.
    pub sent: usize,
    /// Requests served with a `200`.
    pub served: usize,
    /// Requests rejected with a `429` by the cap.
    pub denied: usize,
    /// Times the provider was called: **must equal `served`**.
    pub provider_calls: usize,
    /// Money spent at the end.
    pub spent: MicroUsd,
    /// The cap it was spending against.
    pub cap: MicroUsd,
    /// Reserved and not settled at the end: must be zero.
    pub held: MicroUsd,
    /// Per request: reserved estimate minus real cost. The price of checking first.
    pub reservation_surplus: MicroUsd,
    /// What one request really costs at the configured usage.
    pub actual_per_request: MicroUsd,
}

/// Sends `requests` requests until the cap stops them, and reports what happened.
pub async fn scenario_cap(requests: usize, cap: MicroUsd) -> CappedRun {
    let provider = Arc::new(FakeProvider::new(
        "provider-a",
        vec![Behavior::Ok {
            content: "ok".to_owned(),
            prompt_tokens: 1_000,
            completion_tokens: 500,
        }],
    ));
    let l = lab(vec![Arc::clone(&provider)], cap, 1, 4);
    let price = prices().resolve(MODEL);
    let shape = inspect(&request(4_096, false).body, 4_096);
    let estimate = price.cost(
        shape.estimated_input_tokens,
        shape.max_output_tokens.unwrap_or(0),
    );
    let actual = price.cost(1_000, 500);

    let mut served = 0;
    let mut denied = 0;
    for _ in 0..requests {
        match l.gateway.handle(request(4_096, false)).await.status() {
            200 => served += 1,
            429 => denied += 1,
            other => panic!("unexpected status {other} from a scenario with one healthy provider"),
        }
    }

    CappedRun {
        sent: requests,
        served,
        denied,
        provider_calls: provider.calls(),
        spent: l.meter.spent(TENANT),
        cap,
        held: l.cap.held(NOW),
        reservation_surplus: estimate - actual,
        actual_per_request: actual,
    }
}

/// Money is exact even when the operating metrics are sampled into nothing.
#[derive(Debug, Clone)]
pub struct MoneyRun {
    /// Requests served.
    pub requests: usize,
    /// Money spent, expected to be exactly `requests × per_request`.
    pub spent: MicroUsd,
    /// What an exact count would be.
    pub expected: MicroUsd,
    /// `served` as the meter reports it, **sampled**: 1 in `sample_rate`.
    pub served_as_measured: u64,
    /// The sampling rate used.
    pub sample_rate: u64,
    /// Requests served without the cap: the alarm. Must be zero.
    pub uncovered: u64,
}

/// Runs many requests with a huge sample rate to separate money from metrics.
pub async fn scenario_money(requests: usize, sample_rate: u64) -> MoneyRun {
    let provider = Arc::new(FakeProvider::new(
        "provider-a",
        vec![Behavior::Ok {
            content: "ok".to_owned(),
            prompt_tokens: 1_000,
            completion_tokens: 500,
        }],
    ));
    let l = lab(
        vec![Arc::clone(&provider)],
        usd(1.0).expect("valid cap"),
        sample_rate,
        4,
    );
    let per_request = prices().resolve(MODEL).cost(1_000, 500);

    for _ in 0..requests {
        let status = l.gateway.handle(request(4_096, false)).await.status();
        assert_eq!(status, 200, "the cap was meant to be out of the way here");
    }

    MoneyRun {
        requests,
        spent: l.meter.spent(TENANT),
        expected: per_request * requests as MicroUsd,
        served_as_measured: l.meter.snapshot_for(TENANT).map_or(0, |s| s.served),
        sample_rate,
        uncovered: l.meter.served_uncovered(),
    }
}

/// Everything one run of the lab measured.
#[derive(Debug)]
pub struct Report {
    /// When the run happened, in Unix seconds.
    pub generated_at: u64,
    /// The machine, so a number is never read without its environment.
    pub host: String,
    /// The compiler.
    pub rustc: String,
    /// Scenario: the cap holds in front of the spend.
    pub capped: CappedRun,
    /// Scenario: a provider error moves to the next provider.
    pub failover: SingleRun,
    /// Scenario: a client error does not move anywhere.
    pub client_error: SingleRun,
    /// Scenario: a request that may already have been executed is not retried.
    pub no_double_charge: SingleRun,
    /// Scenario: money exact, metrics sampled.
    pub money: MoneyRun,
    /// Scenario: streaming is not accumulated.
    pub streaming: SingleRun,
    /// Scenario: a real agent, over a real socket, through this gateway.
    pub e2e: Option<e2e::E2eRun>,
}

/// Runs every scenario. This is the whole lab.
pub async fn run_lab() -> Report {
    let healthy = || {
        vec![Behavior::Ok {
            content: "ok".to_owned(),
            prompt_tokens: 1_000,
            completion_tokens: 500,
        }]
    };

    // Each scenario gets its own providers and its own gateway: sharing them would make
    // one scenario's counters part of another scenario's numbers.
    let flaky = Arc::new(FakeProvider::new(
        "provider-a",
        vec![Behavior::Responds {
            status: 503,
            body: r#"{"error":"service unavailable"}"#.to_owned(),
        }],
    ));
    let good = Arc::new(FakeProvider::new("provider-b", healthy()));
    let failover = run_one(
        &lab(vec![flaky.clone(), good.clone()], usd(1.0).unwrap(), 1, 4),
        &[flaky, good],
        4_096,
        false,
    )
    .await;

    let wrong = Arc::new(FakeProvider::new(
        "provider-a",
        vec![Behavior::Responds {
            status: 400,
            body: r#"{"error":{"message":"unknown model"}}"#.to_owned(),
        }],
    ));
    let good = Arc::new(FakeProvider::new("provider-b", healthy()));
    let client_error = run_one(
        &lab(vec![wrong.clone(), good.clone()], usd(1.0).unwrap(), 1, 4),
        &[wrong, good],
        4_096,
        false,
    )
    .await;

    let lost = Arc::new(FakeProvider::new("provider-a", vec![Behavior::SentUnknown]));
    let good = Arc::new(FakeProvider::new("provider-b", healthy()));
    let no_double_charge = run_one(
        &lab(vec![lost.clone(), good.clone()], usd(1.0).unwrap(), 1, 4),
        &[lost, good],
        4_096,
        false,
    )
    .await;

    let chunked = Arc::new(FakeProvider::new(
        "provider-a",
        vec![Behavior::Stream(vec![
            r#"{"token":"hel"}"#.to_owned(),
            r#"{"token":"lo"}"#.to_owned(),
        ])],
    ));
    let streaming = run_one(
        &lab(vec![chunked.clone()], usd(1.0).unwrap(), 1, 4),
        &[chunked],
        4_096,
        true,
    )
    .await;

    Report {
        generated_at: SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .map_or(0, |d| d.as_secs()),
        host: format!("{} {}", std::env::consts::OS, std::env::consts::ARCH),
        rustc: rustc_version(),
        capped: scenario_cap(10, micros(7)).await,
        failover,
        client_error,
        no_double_charge,
        money: scenario_money(100, 1_000).await,
        streaming,
        e2e: Some(e2e::scenario_e2e(Path::new(".")).await),
    }
}

impl Report {
    /// The report as markdown, ready to be committed in `reports/`.
    ///
    /// Long on purpose: it is a report template, and splitting it into pieces would
    /// hide the only thing that matters here — what a reader sees.
    #[allow(clippy::too_many_lines)]
    pub fn markdown(&self) -> String {
        let usd = |m: MicroUsd| format!("{:.6} USD", m as f64 / 1_000_000.0);
        let calls = |r: &SingleRun| {
            r.calls
                .iter()
                .map(|(name, n)| format!("{name}: {n}"))
                .collect::<Vec<_>>()
                .join(", ")
        };

        format!(
            r"# llmlab — measured behaviour of the gateway

Generated {generated} (unix) · host: {host} · {rustc} · llmgateway pinned by Cargo.lock.

Every number below comes from running the real gateway code in this process, with a fake
provider and no network. `make lab` regenerates this file; `cargo test` asserts it again.

## 1. The cap holds in front of the spend

10 requests, a cap of {cap}, one healthy provider, usage 1000 in / 500 out per request.

| measure | value |
|---|---|
| requests sent by the client | {sent} |
| served with 200 | {served} |
| rejected with 429 by the cap | {denied} |
| times the provider was called | {provider_calls} |
| money spent | {spent} |
| cap | {cap} |
| reserved and not settled at the end | {held} |
| real cost of one request | {actual} |
| reserved estimate minus real cost | {surplus} |

The provider was called exactly {provider_calls} times: a rejected request never reaches
it, which is the difference between a cap and a report. The reservation is pessimistic by
{surplus} per request — the estimate assumes the maximum output, the real response used
less. That surplus is why the cap rejects earlier than pure spending would: checking
before the call costs a little accuracy and buys the guarantee.

## 2. Failover: a provider error moves to the next provider

| measure | value |
|---|---|
| status the client saw | {failover_status} |
| provider that served it | {failover_provider} |
| provider calls | {failover_calls} |
| money spent | {failover_spent} |

## 3. Client error: it does not move anywhere

A 400 from the first provider is the client's fault, so no second provider is tried.

| measure | value |
|---|---|
| status the client saw | {client_status} |
| provider calls | {client_calls} |
| money spent | {client_spent} |

## 4. A request that may already have been executed is not retried

The first provider took the request and never answered: it may have executed it. Retrying
could charge twice, so the gateway stops and reports a failure.

| measure | value |
|---|---|
| status the client saw | {lost_status} |
| provider calls | {lost_calls} |
| money spent | {lost_spent} |
| money still reserved | {lost_held} |

## 5. Money is exact, operating metrics are sampled

{money_requests} requests, sampling rate 1 in {sample_rate}.

| measure | value |
|---|---|
| money spent | {money_spent} |
| money expected ({money_requests} × per request) | {money_expected} |
| `served` as the meter reports it | {money_served} |
| requests served without the cap | {money_uncovered} |

The two rows in the middle are the point: the money is exact to the micro-dollar, while
the operating counter reports {money_served} because it only counts 1 event in
{sample_rate}. That is ADR 0005 made visible — invoice on the money, dashboard on the
counter, and never the other way round.

## 6. Streaming is forwarded, not accumulated

| measure | value |
|---|---|
| status | {stream_status} |
| forwarded as a stream | {stream_streamed} |
| money spent here | {stream_spent} |

Zero, and it is declared rather than surprising: the usage of a streamed response arrives
in its last chunk, which the gateway never buffers, so the cost of a stream is metered
downstream by the client.

{e2e}
",
            generated = self.generated_at,
            host = self.host,
            rustc = self.rustc,
            cap = usd(self.capped.cap),
            sent = self.capped.sent,
            served = self.capped.served,
            denied = self.capped.denied,
            provider_calls = self.capped.provider_calls,
            spent = usd(self.capped.spent),
            held = usd(self.capped.held),
            actual = usd(self.capped.actual_per_request),
            surplus = usd(self.capped.reservation_surplus),
            failover_status = self.failover.status,
            failover_provider = self.failover.provider.as_deref().unwrap_or("(nobody)"),
            failover_calls = calls(&self.failover),
            failover_spent = usd(self.failover.spent),
            client_status = self.client_error.status,
            client_calls = calls(&self.client_error),
            client_spent = usd(self.client_error.spent),
            lost_status = self.no_double_charge.status,
            lost_calls = calls(&self.no_double_charge),
            lost_spent = usd(self.no_double_charge.spent),
            lost_held = usd(self.no_double_charge.held),
            money_requests = self.money.requests,
            sample_rate = self.money.sample_rate,
            money_spent = usd(self.money.spent),
            money_expected = usd(self.money.expected),
            money_served = self.money.served_as_measured,
            money_uncovered = self.money.uncovered,
            stream_status = self.streaming.status,
            stream_streamed = self.streaming.streamed,
            stream_spent = usd(self.streaming.spent),
            e2e = self
                .e2e
                .as_ref()
                .map_or_else(String::new, e2e::E2eRun::markdown),
        )
    }

    /// The same numbers as JSON, for whatever wants to diff them over time.
    pub fn json(&self) -> String {
        let single = |r: &SingleRun| {
            serde_json::json!({
                "status": r.status,
                "provider": r.provider,
                "calls": r.calls.iter().cloned().collect::<BTreeMap<_, _>>(),
                "spent_micro_usd": r.spent,
                "held_micro_usd": r.held,
                "streamed": r.streamed,
            })
        };
        let value = serde_json::json!({
            "generated_at": self.generated_at,
            "host": self.host,
            "rustc": self.rustc,
            "capped": {
                "sent": self.capped.sent,
                "served": self.capped.served,
                "denied": self.capped.denied,
                "provider_calls": self.capped.provider_calls,
                "spent_micro_usd": self.capped.spent,
                "cap_micro_usd": self.capped.cap,
                "held_micro_usd": self.capped.held,
                "reservation_surplus_micro_usd": self.capped.reservation_surplus,
            },
            "failover": single(&self.failover),
            "client_error": single(&self.client_error),
            "no_double_charge": single(&self.no_double_charge),
            "money": {
                "requests": self.money.requests,
                "spent_micro_usd": self.money.spent,
                "expected_micro_usd": self.money.expected,
                "served_as_measured": self.money.served_as_measured,
                "sample_rate": self.money.sample_rate,
                "uncovered": self.money.uncovered,
            },
            "streaming": single(&self.streaming),
            "e2e": match &self.e2e {
                None => serde_json::Value::Null,
                Some(run) => serde_json::json!({
                    "ran": run.ran,
                    "skip_reason": run.skip_reason,
                    "gateway_spent_micro_usd": run.gateway_spent,
                    "agent_spent_micro_usd": run.agent.spent_micro_usd,
                    "difference_micro_usd": run.difference(),
                    "steps": run.agent.steps,
                    "stop_reason": run.agent.stop_reason,
                    "replay_equal": run.agent.replay_equal,
                    "provider_calls": run.provider_calls,
                    "denied_label": run.denied.as_ref().and_then(|d| d.error.clone()),
                }),
            },
        });
        serde_json::to_string_pretty(&value).unwrap_or_else(|_| "{}".to_owned())
    }
}

fn rustc_version() -> String {
    std::process::Command::new("rustc")
        .arg("--version")
        .output()
        .ok()
        .and_then(|o| String::from_utf8(o.stdout).ok())
        .map_or_else(|| "rustc unknown".to_owned(), |v| v.trim().to_owned())
}

fn ok_body(content: &str, prompt_tokens: u64, completion_tokens: u64) -> String {
    serde_json::json!({
        "choices": [{"message": {"content": content}}],
        "usage": {"prompt_tokens": prompt_tokens, "completion_tokens": completion_tokens}
    })
    .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[tokio::test]
    async fn a_rejected_request_never_reaches_the_provider() {
        let run = scenario_cap(10, micros(7)).await;
        assert!(
            run.denied > 0,
            "the cap must actually stop something: {run:?}"
        );
        assert!(run.served > 0);
        assert_eq!(
            run.provider_calls, run.served,
            "every provider call must correspond to a served request: {run:?}"
        );
        assert!(run.spent <= run.cap, "the cap must hold: {run:?}");
        assert_eq!(run.held, 0, "no reservation may stay pending: {run:?}");
    }

    #[tokio::test]
    async fn a_provider_error_moves_to_the_next_provider() {
        let a = Arc::new(FakeProvider::new(
            "provider-a",
            vec![Behavior::Responds {
                status: 503,
                body: "{}".to_owned(),
            }],
        ));
        let b = Arc::new(FakeProvider::new(
            "provider-b",
            vec![Behavior::Ok {
                content: "ok".to_owned(),
                prompt_tokens: 10,
                completion_tokens: 5,
            }],
        ));
        let run = one(&[Arc::clone(&a), Arc::clone(&b)], 4_096, false).await;
        assert_eq!(run.status, 200);
        assert_eq!(run.provider.as_deref(), Some("provider-b"));
        assert_eq!(a.calls(), 1);
        assert_eq!(b.calls(), 1);
    }

    #[tokio::test]
    async fn a_client_error_does_not_reach_a_second_provider() {
        let a = Arc::new(FakeProvider::new(
            "provider-a",
            vec![Behavior::Responds {
                status: 400,
                body: "{}".to_owned(),
            }],
        ));
        let b = Arc::new(FakeProvider::new(
            "provider-b",
            vec![Behavior::Ok {
                content: "ok".to_owned(),
                prompt_tokens: 10,
                completion_tokens: 5,
            }],
        ));
        let run = one(&[Arc::clone(&a), Arc::clone(&b)], 4_096, false).await;
        assert_eq!(run.status, 400);
        assert_eq!(b.calls(), 0, "a client error is not retried anywhere");
    }

    #[tokio::test]
    async fn a_request_that_may_have_been_executed_is_not_retried() {
        let a = Arc::new(FakeProvider::new("provider-a", vec![Behavior::SentUnknown]));
        let b = Arc::new(FakeProvider::new(
            "provider-b",
            vec![Behavior::Ok {
                content: "ok".to_owned(),
                prompt_tokens: 10,
                completion_tokens: 5,
            }],
        ));
        let run = one(&[Arc::clone(&a), Arc::clone(&b)], 4_096, false).await;
        assert_eq!(run.status, 502);
        assert_eq!(b.calls(), 0, "retrying could charge twice");
        assert_eq!(run.spent, 0, "nothing was served, so nothing is owed");
        assert_eq!(run.held, 0, "the reservation must be released");
    }

    #[tokio::test]
    async fn money_is_exact_while_metrics_are_sampled() {
        let run = scenario_money(100, 1_000).await;
        assert_eq!(
            run.spent, run.expected,
            "money must be exact to the micro-dollar: {run:?}"
        );
        assert_eq!(
            run.served_as_measured, 0,
            "with 1 in 1000 sampling, 100 events are counted zero times: {run:?}"
        );
        assert_eq!(run.uncovered, 0, "nothing may be served without the cap");
    }

    #[tokio::test]
    async fn streaming_is_forwarded_and_not_metered_here() {
        let provider = Arc::new(FakeProvider::new(
            "provider-a",
            vec![Behavior::Stream(vec!["{\"token\":\"hel\"}".to_owned()])],
        ));
        let run = one(&[provider], 4_096, true).await;
        assert_eq!(run.status, 200);
        assert!(run.streamed, "the stream must not become a whole body");
        assert_eq!(run.spent, 0, "usage on a stream is metered downstream");
    }

    #[tokio::test]
    async fn the_report_is_generated_and_self_consistent() {
        let report = run_lab().await;
        let markdown = report.markdown();
        assert!(markdown.contains("## 1. The cap holds in front of the spend"));
        assert!(markdown.contains("## 6. Streaming is forwarded"));
        assert_ne!(report.json(), "");
        assert!(
            report.failover.calls.iter().all(|(_, n)| *n > 0),
            "a provider in a failover scenario must report its call count: {:?}",
            report.failover.calls
        );
        assert_eq!(
            report.client_error.calls.get(1).map(|(_, n)| *n),
            Some(0),
            "the second provider must show zero calls: {:?}",
            report.client_error.calls
        );
        assert_eq!(report.capped.sent, 10);
    }
}
